[package]
name = "a-cuanto-api"
version = "0.1.0"
authors = ["efredz <efredzb@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.1"
rocket_contrib = "0.4.1"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.14.1"
serde = { version = "1.0.92", features = ["derive"] }